### ISSUE TITLE
Versão de Suporte.

### ISSUE THREAD

**Issue by gblnovaes** [Flip-Payments/connect-sdk-android#2]
Apartir de qual versão da api , o flip connect é suportado ?

**Comment by mgribel** [comment]
@gblnovaes essa sdk não é mais suportada. 
Favor utilizar a url abaixo:
[https://github.com/stone-payments/onestap-sdk-android](https://github.com/stone-payments/onestap-sdk-android)
Para onestap-sdk-android a minSDK é api 16.


Att, 
Fico a disposição para qualquer esclarecimento.
